# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFMZjCVh5VFmRwlH4zxiS3nTGDhrveyD
"""

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files

# تابعی برای بارگذاری و تغییر اندازه تصویر
def load_and_resize_image(image_path):
    img = Image.open(image_path)
    img = img.resize((900, 900))  # تغییر اندازه به 900x900
    return np.array(img)

# تابعی برای پیمایش و استخراج پیکسل‌ها
def extract_pixels(image):
    rows, cols, _ = image.shape
    output_images = [np.zeros((100, 100, 3), dtype=np.uint8) for _ in range(9)]

    # پیمایش تصویر
    for iteration in range(9):
        for i in range(0, rows - 2, 3):  # حرکت 3 پیکسل به جلو
            for j in range(0, cols - 2, 3):
                # انتخاب پیکسل چپ‌ترین و بالا‌ترین
                pixel = image[i, j]
                output_images[iteration][(i // 3) % 100, (j // 3) % 100] = pixel

    return output_images

# تابعی برای نمایش تصاویر
def display_images(original_image, output_images):
    plt.figure(figsize=(12, 12))

    plt.subplot(4, 4, 1)
    plt.imshow(original_image)
    plt.title('Original Image')
    plt.axis('off')

    for i, img in enumerate(output_images):
        plt.subplot(4, 4, i + 2)
        plt.imshow(img)
        plt.title(f'Image {i + 1}')
        plt.axis('off')

    plt.show()

# بارگذاری تصویر از کاربر
uploaded = files.upload()

# فرض می‌کنیم کاربر فقط یک تصویر بارگذاری کرده است
image_path = list(uploaded.keys())[0]

# بارگذاری و تغییر اندازه تصویر
original_image = load_and_resize_image(image_path)

# استخراج پیکسل‌ها به تصاویر 100x100
output_images = extract_pixels(original_image)

# نمایش تصویر اصلی و تصاویر 100x100
display_images(original_image, output_images)